### PR TITLE
Update to 8.11

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Comment by razzeee** [comment]
@faveoled any chance, that you can find time to run the python script?

**Comment by faveoled** [comment]
Ran it. What's your error btw?

**Comment by faveoled** [comment]
```
Total spawn time to start the pgAdmin4 server: 0.013 Sec
Failed to launch pgAdmin4. Error:
Error: spawn /app/pgadmin4/bin/resources/app/src/js/usr/bin/python ENOENT
```

**Comment by razzeee** [comment]
> Ran it. What's your error btw?

Wasn't near a PC capable of running that

**Comment by razzeee** [comment]
I guess joining the paths with the base path breaks this https://github.com/pgadmin-org/pgadmin4/blob/master/runtime/src/js/misc.js#L60

**Comment by razzeee** [comment]
Updated to 8.11

**Comment by razzeee** [comment]
@faveoled I'm not 100% sure how to get the pip part working again

**Comment by faveoled** [comment]
Your changes look fine to me.
```
ERROR: No matching distribution found for importlib-metadata>=4.11.4; python_version < "3.12"
```
I can see two possible causes of this error:
* Your local python version differs from the one in the Flatpak runtime
* flatpak-pip-generator doesn't properly resolve this conditional (and transitive) dependency

**Comment by razzeee** [comment]
Thanks it indeed was the python version

**Pull request merged**
